# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookr', '0003_auto_20160417_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='No authors found', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='No title found', max_length=200),
        ),
    ]
