# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookr', '0004_auto_20160417_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.BigIntegerField()),
                ('title', models.CharField(default='No title found', max_length=200)),
                ('author', models.CharField(default='No authors found', max_length=200)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.AddField(
            model_name='book',
            name='booktype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookr.BookType'),
        ),
    ]
