# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookr', '0005_auto_20160418_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(null=True, upload_to='bookr/images/uploaded/'),
        ),
        migrations.AlterField(
            model_name='booktype',
            name='picture',
            field=models.ImageField(null=True, upload_to='bookr/images/scraped/'),
        ),
    ]
